### ISSUE TITLE
자바스크립트에 대한 전반적인 설명을 해줄 수 있는 글, 동영상 필요(Hacktoberfest)

### ISSUE THREAD

**Issue by DaeguDude** [DaeguDude/jasmine#19]
핵토버페스트 기념으로 누군가가 자바스크립트에 대한 전반적인 설명을 해줄 수 있는 글과 동영상을 신입자료에 첨부해주면 좋을 것 같습니다.

> [핵토버페스트(Hacktoberfest)](https://medium.com/@bawantharathnayaka/what-is-hacktoberfest-and-how-can-a-beginner-contribute-39cf2081804e): 핵토버페스트란 [깃허브](https://github.com/)가 [디지털 오션](https://www.digitalocean.com/)과 주최하는 축하행사로, 10월 한 달 동안 오픈 소스에 기여하는 것을 장려하는 행사입니다.

지금 필요한 것은, [자바스크립트 신입 강의](https://github.com/DaeguDude/jasmine/tree/master/jsCourse) 문서에서 제목 밑에, 너무 세세하게 들어가지 않고 자바스크립트에 대한 전반적인 설명을 해줄 수 있는 글이나, 동영상을 첨부해준다면 아주 좋을 것 같습니다. 

예를 들어, 

# 자바스크립트를 시작하기 전에 보면 좋을 것들

[자바스크립트 배우기전 꼭 봐야할 영상](https://www.youtube.com/watch?v=wcsVjmHrUQg&list=PLv2d7VI9OotTVOL4QmPfvJWPJvkmv6h-2&ab_channel=%EB%93%9C%EB%A6%BC%EC%BD%94%EB%94%A9by%EC%97%98%EB%A6%AC)

이런 식으로 해주시면 됩니다.

만약에, 기여하시고 싶으신 분은 다른 분과 겹치지 않게 댓글을 통해 알려주세요

**Comment by hokidoki** [comment]
## 자바스크립트 배우기전에 보면 좋을 동영상 목록 

**노마드 코더**

https://www.youtube.com/watch?v=rjiU7S5Q9-w // 개발자 및 프로그래머가 되려면 얼마나 개 빡시게 살아야 하는지 간단하게 설명해주는 영상

https://www.youtube.com/watch?v=ODa9mY2bEEc // 2020년 최신 트렌드를 반영한 웹 개발 로드맵

**Comment by DaeguDude** [comment]
@hokidoki 이것도 자스민 신입 문서 강의를 직접 편집하여서 PR좀 해주세요.

그리고 링크는, 링크주소를 바로 띄우지 말고, 글을 클릭하면 링크를 바로 따라갈 수 있게 해주세요.

예를 들어,

[개발자가 되려면 얼마나 걸리나요?](https://www.youtube.com/watch?v=rjiU7S5Q9-w&ab_channel=%EB%85%B8%EB%A7%88%EB%93%9C%EC%BD%94%EB%8D%94NomadCoders)
