### ISSUE TITLE
구글링을 할 때 참조할 만 한 사이트들 추가하기(핵토버페스트)

### ISSUE THREAD

**Issue by DaeguDude** [DaeguDude/jasmine#20]
핵토버페스트의 일환으로, 구글링을 할 때 참조할 만한 사이트들을 추가해주었으면 합니다.

> [핵토버페스트(Hacktoberfest)](https://medium.com/@bawantharathnayaka/what-is-hacktoberfest-and-how-can-a-beginner-contribute-39cf2081804e): 핵토버페스트란 [깃허브](https://github.com/)가 [디지털 오션](https://www.digitalocean.com/)과 주최하는 축하행사로, 10월 한 달 동안 오픈 소스에 기여하는 것을 장려하는 행사입니다.

[자스민 신입 강의](https://github.com/DaeguDude/jasmine/tree/master/jsCourse)란을 보면, 문법에 치중한 강의로 구글링을 할 때 어떤 사이트를 참조하면 좋을지 제대로 자료가 없습니다. 여기에 구글링 할 때 참조할 만한 사이트들을 추가해주면 좋을 것 같습니다.

예를 들어,

# 구글링 참고 사이트
- [stackoverflow](https://stackoverflow.com/)

이런 식으로 하여주시면 됩니다.

만약에, 기여하시고 싶으신 분은 다른 분과 겹치지 않게 댓글을 통해 알려주세요

**Comment by hokidoki** [comment]
## 자바스크립트 튜토리얼  동영상 강좌

**생활코딩** : http://opentutorials.org 

자스민 이종호, 이진욱, 김언동, 김상학, 엄성현 등 많은 사람들이 추천하는 명실상부 대한민국 최강 웹개발 입문 동영상 튜토리얼 사이트 . html/css , javascript , node.js , php, Oauth 등 다양한 예제가 한국어로 준비되어 있고 윈도우 사용자를 위한 배려도 일부 존재 . 

## 자바스크립트 및 CSS 상세 설명

**MDN** : https://developer.mozilla.org/ko/

다양한 html/css , javascript 에 태그, 선택자, 함수 설명 등 기본 예제 또한 존재하여 이 분야의 사람이라면 자주 방문하는 사이트 

## 자바스크립트 국내 사용자 모임 

**JavascriptForum** : https://jsdev.kr 

국내 자바스크립트 사용자들이 다양한 이슈에 대해 한국어로 질문하고, 설명해주는 공간 . 예전에는 리액트 외에도 앵귤러, 제이쿼리 등 활발히 질문하고 답변 해주었으나, 앵귤러, 뷰, 제이쿼리는 인기가 적다.

**Comment by DaeguDude** [comment]
@hokidoki  오 너무 좋습니다 ㅋㅋㅋ 자스민 신입 강의란 편집해서 PR 해주시겠어요?
